### ISSUE TITLE
Problem displaying the menu

### ISSUE THREAD

**Issue by safaritn** [Astrarium/Astrarium#110]
Hi,
I'm very pleased of your excellent Astrarium Software. Good luck for increasing development for that.
After installing and executing, the Menu software display "{Menu.Map}" althoug the name it self. How can I correct this ? Thnak you in avdance.

**Comment by AlexanderKrutov** [comment]
Hello,
thank you for the positive feedback about the app!
Seems that Astrarium was not installed correctly, try to reinstall it. Also could you be so kind to attach a screenshot with the problem.

**Comment by safaritn** [comment]
This is a capture of the problem:
![image](https://github.com/Astrarium/Astrarium/assets/26029048/40071a0f-1990-4b2b-bb79-d6a9dd3a16b0)

**Comment by safaritn** [comment]
This is the problem :
![image](https://github.com/Astrarium/Astrarium/assets/26029048/3a18cd2d-b46b-470e-b27c-0453fee0a1a8)

**Comment by Atque** [comment]
I also have this problem. A solution is to change language to Russian and then back to English. However, this needs to be done every time Astrarium is restarted.

**Comment by AlexanderKrutov** [comment]
Finally I've found the root cause. This will be fixed in the upcoming release. Thanks everyone for reporting the problem.
