### ISSUE TITLE
Menu displaying problem

### ISSUE THREAD

**Issue by safaritn** [Astrarium/Astrarium#116]
Hi,

When I run the program, the menu displays "{" and "}" characters !
![image](https://github.com/Astrarium/Astrarium/assets/26029048/f87d9cd3-3788-4498-9c90-ee9e636167ea)
How can I fix this problem ? Thank you.

**Comment by Atque** [comment]
See #110.

**Comment by AlexanderKrutov** [comment]
Closed as duplicate of #110 , see that issue for details.
