### ISSUE TITLE
Compile for arm android

### ISSUE THREAD

**Issue by ultrapre** [Astrarium/Astrarium#26]
Hi ! Thank you for your excellent work. How about cross-compiling a version for armv7 Android? Working on multi-platforms may be more interesting.

**Comment by AlexanderKrutov** [comment]
Hi, thanks for your response.
The source code has a lot of OS-specific dependencies (Windows API calls, external DLLs and etc.), also it's written with WPF, so it would be almost impossible to port to Android without significant changes. Honestly speaking, it's almost equal to writing a second planetarium software, with only a little part of shared code.
Anyway, thank you for opening the issue!
